/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.56
 * Generated at: 2017-04-11 08:14:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/Front1.jsp", Long.valueOf(1469380284000L));
    _jspx_dependants.put("/bottom.html", Long.valueOf(1469291012000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write(' ');
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title></title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"FRONT.css\">\r\n");
      out.write("<script src=\"//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function validate()\r\n");
      out.write("{\r\n");
      out.write("\tif (document.login.t1.value==\"\")\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"PLEASE ENTER YOUR USERID!\");\r\n");
      out.write("\t\tdocument.login.t1.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tif (document.login.t2.value==\"\")\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"PLEASE ENTER YOUR PASSWORD!\");\r\n");
      out.write("\t\tdocument.login.t2.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"body\">\r\n");
      out.write("<div class=\"image\" align=\"center\">\r\n");
      out.write("<img class=\"img1\" src=\"./images/COP.jpg\" width=\"120\" height=\"100\"/>\r\n");
      out.write("<img src=\"./images/download.jpg\" width=\"120\" height=\"100\" />\r\n");
      out.write("<img src=\"./images/IMG.png\" width=\"200\" height=\"100\"/> \r\n");
      out.write("<img src=\"./images/imagesr.png\" width=\"120\" height=\"100\" />\r\n");
      out.write("<img class=\"img0\" src=\"./images/flag.jpg\" width=\"120\" height=\"100\" /> </div>\r\n");
      out.write("<div id=\"top\" align=\"center\" style=\"color:blue;\">\r\n");
      out.write("<h1><marquee style=\"background-color:black;color:white;font-size:25px\" behavior=\"scroll\" direction=\"left\">Welcome To E-Cops Online Portal</marquee>\r\n");
      out.write("<img src=\"./gif/misc025.gif\" style=\"position:absolute; left:20px; height:33px; float:right; top: 50px; width: 200px\" />\r\n");
      out.write("<img src=\"./gif/misc025.gif\" style=\"position:absolute; right:20px; height:33px; float:right; top: 50px; width: 200px\" /></h1>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"btn\" align=\"center\">\r\n");
      out.write("<div class=\"menu\">\r\n");
      out.write("      <ul>\r\n");
      out.write("        <li> \r\n");
      out.write("        <a>ADMIN</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li> <a href=\"http://cbi.nic.in/rt_infoact/rti.php\">Policestations</a> </li>\r\n");
      out.write("        <li> <a href=\"http://cbi.nic.in/rt_infoact/rti.php\">Employees</a> \r\n");
      out.write("           <ul>\r\n");
      out.write("           <li><a href=\"policelogin.jsp\">Employees Information</a></li>\r\n");
      out.write("           <li><a href=\"policereg.jsp\">Employees Registration</a></li>\r\n");
      out.write("           <li><a href=\"policelogin.jsp\">Job Records</a></li>\r\n");
      out.write("           <li><a href=\"\">Employees Rights</a></li>\r\n");
      out.write("           </ul>        \r\n");
      out.write("        </li>\r\n");
      out.write("        <li> <a href=\"Register.jsp\">Public Registration</a> </li>\r\n");
      out.write("        <li> <a href=\"http://cbi.nic.in/wantedbycbi.php\">CBI\r\n");
      out.write("          \r\n");
      out.write("        </a>\r\n");
      out.write("          <ul>\r\n");
      out.write("            <li> <a href=\"http://cbi.nic.in/rnotice/notices.php\" title=\"\">Interpol Red Notices</a> </li>\r\n");
      out.write("            <li> <a href=\"http://cbi.nic.in/rnotice/notices_yellow.php\" title=\"\">Interpol Yellow Notices</a> </li>\r\n");
      out.write("            <li> <a href=\"http://cbi.nic.in/wanted/wanted.php\" title=\"\">Missing / Kidnap</a> </li>\r\n");
      out.write("            <li> <a href=\"http://cbi.nic.in/wanted/rewards.php\" title=\"\">Announced Rewards</a> </li>\r\n");
      out.write("\t\t\t<li> <a href=\"http://cbi.nic.in/warrant/warrant.php\" title=\"\">Warrant</a> </li>\r\n");
      out.write("\t\t\t<li> <a href=\"http://cbi.nic.in/sketch/sketch.php\" title=\"\">Sketch</a> </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("          \r\n");
      out.write("        </li>\r\n");
      out.write("        <li> <a>Links</a>\r\n");
      out.write("        \r\n");
      out.write("          <ul>\r\n");
      out.write("            <li> <a href=\"http://www.cbiacademy.gov.in/\" title=\"\" target=\"new\">Ecops Academy</a> </li>\r\n");
      out.write("            <li> <a href=\"http://cbi.nic.in/cbigallery.php\">Latest News</a> </li>\r\n");
      out.write("            <li> <a href=\"http://cbi.nic.in/pg.php\">Photo Gallery</a> </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("         \r\n");
      out.write("        </li>\r\n");
      out.write("       \r\n");
      out.write("        <li> <a href=\"http://cbi.nic.in/rt_infoact/rti.php\">Women</a> </li>\r\n");
      out.write("        <li> <a href=\"http://cbi.nic.in/rt_infoact/rti.php\">Traffic</a> </li>\r\n");
      out.write("         <li> <a href=\"\">About Us</a>\r\n");
      out.write("          <ul>\r\n");
      out.write("            <li> <a href=\"\">Crime Manuals</a> </li>\r\n");
      out.write("            <li> <a href=\"\">Admin Manuals</a> </li>\r\n");
      out.write("            <li> <a href=\"\">History</a> </li>\r\n");
      out.write("            <li><a href=\"\">Ecops Employee Corner</a></li>\r\n");
      out.write("            <li> <a href=\"\">Senior Officers</a> </li>\r\n");
      out.write("\t\t  </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li> <a href=\"http://cbi.nic.in/rt_infoact/rti.php\">RTI</a> </li>\r\n");
      out.write("        <li> <a href=\"http://cbi.nic.in/tender.php\">Tender</a> </li>\r\n");
      out.write("        <li> <a href=\"http://cbi.nic.in/faq.php\">FAQs</a> </li>\r\n");
      out.write("        <li> <a href=\"http://cbi.nic.in/sitemap.php\">Site Map</a> </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("  </div>   \r\n");
      out.write("<div align=\"right\">\r\n");
      out.write("<strong>\r\n");
      out.write("<a href=\"home.html\"><img src=\"./images/home.png\" width=\"63\" height=\"57\"/>Home</a>\r\n");
      out.write("<a href=\"contact.jsp\"><img src=\"./images/c.png\" width=\"63\" height=\"57\"/>Contact us</a>\r\n");
      out.write("<a href=\"http://www.facebook.com\"><img src=\"./images/facebookIcon.jpg\"  width=\"40\" height=\"35\"/></a>\r\n");
      out.write("<a href=\"http://www.twitter.in\"><img src=\"./images/twitterIcon.jpg\"  width=\"40\" height=\"35\"/></a>\r\n");
      out.write("<a href=\"http://www.linkedin.com\"><img src=\"./images/linkedinIcon.jpg\" width=\"40\" height=\"35\"/></a>\r\n");
      out.write("<a href=\"http://www.googleplus.com\"><img src=\"./images/googlePlusIcon.jpg\" width=\"40\" height=\"35\"/></a>\r\n");
      out.write("</strong>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("   \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Register</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"loader.css\">\r\n");
      out.write("<marquee style=\"background-color:black;color:white;font-size:25px\" behavior=\"scroll\" direction=\"left\">Register to our online portal to get updates</marquee>\r\n");
      out.write("<h1 style=\"color:blue;\" align=\"center\">REGISTRATION FORM</h1>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div style=\"background-color:white\" align=\"center\">\r\n");
      out.write("<form  action=\"ecopsdbms.jsp\" method=\"post\" style=\"font-size:25px\"  align=\"center\" >\r\n");
      out.write("<table>\r\n");
      out.write("<tbody>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>\r\n");
      out.write("First Name:<input type=\"text\" style=\"font-size:15px\" placeholder=Fname name=\"fname\" required>\r\n");
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.write("<p>  Last Name:<input type=\"text\" style=\"font-size:15px\" placeholder=Lname name=\"lname\" required></p>\r\n");
      out.write("</td>  \r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>\r\n");
      out.write("Age:<input type=\"number\" style=\"font-size:15px\" placeholder=Age name=\"age\" required>\r\n");
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.write("<p>Sex:<input type=\"radio\" name=\"sex\" value=\"Male\" name=\"sex\" checked >Male\r\n");
      out.write("<input type=\"radio\"  name=\"sex\" value=\"Female\" name=\"sex\">Female</p>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write(" <tr>\r\n");
      out.write("<td>\r\n");
      out.write("<p>D.O.B:<input type=\"number\" style=\"font-size:15px\" placeholder=D.O.B name=\"dob\" ></p>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write(" <td>\r\n");
      out.write(" <p style=\"color:purple; text-decoration:underline\">Residential address:</p>\r\n");
      out.write("<p>Country:<label>\r\n");
      out.write("  <select name=\"country\">\r\n");
      out.write("    <option value=\"Ind\">India</option>\r\n");
      out.write("    <option value=\"ban\">Bangladesh</option>\r\n");
      out.write("    <option value=\"pak\">Pakistan</option>\r\n");
      out.write("    <option value=\"sri\">Srilanka</option>\r\n");
      out.write("    <option value=\"aus\">Australia</option>\r\n");
      out.write("    <option value=\"cin\">China</option>\r\n");
      out.write("    <option value=\"afgan\">Afganisthan</option>\r\n");
      out.write("    <option value=\"Uk\">United Kingdom</option>\r\n");
      out.write("    <option value=\"Us\">United States</option>\r\n");
      out.write("  </select>\r\n");
      out.write("</label></p>\r\n");
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.write("<p>District:<input type=\"text\" style=\"font-size:15px\" placeholder=District name=\"district\"required></p>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>\r\n");
      out.write("City:<input type=\"text\" style=\"font-size:15px\" placeholder=City name=\"city\" required>\r\n");
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.write("<p>Pin Code:<input type=\"text\"  style=\"font-size:15px\" placeholder=\"Pin Code\" name=\"pin-code\" required></p>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</div>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>\r\n");
      out.write("<p>Profession:<input type=\"text\" style=\"font-size:15px\" placeholder=profession name=\"profession\" required></p>\r\n");
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.write("<p>Email:<input type=\"text\"  style=\"font-size:15px\" placeholder=Email name=\"e-mail\" required></p>\r\n");
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.write("<p>Mobile No:<input type=\"text\" style=\"font-size:15px\" placeholder=\"mobile number\" name=\"mobile no\" required></p>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>\r\n");
      out.write("<h2>\r\n");
      out.write("Choose a username\r\n");
      out.write("</h2>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>\r\n");
      out.write("<p>User_Id:<input type=\"text\" placeholder=username name=\"uname\" required></p>\r\n");
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.write("<p>Password:<input type=\"password\" placeholder=password name=\"pwd\" required></p>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>\r\n");
      out.write("<p><input type=\"submit\" style=\"color:blue;  background-color:rgb(202,202,202)\" value=\"I accept terms and conditions\"></p>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>\r\n");
      out.write("<button id=\"submit\" class=\"button\" value=\"submit\" name=\"Register\">submit</button>\r\n");
      out.write("<button id=\"reset\" class=\"button\" value=\"reset\" name=\"reset\">reset</button>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>\r\n");
      out.write("<h3 style=\"color:red\">If You Are Already Registered. Click<a href=\"Front.jsp\"> Login</a>\r\n");
      out.write("</h3>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</tbody>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"c\" align=\"center\">\r\n");
      out.write("<h3>Write comment about us.</h3>\r\n");
      out.write("<textarea name=\"comment\" rows=\"6\" cols=\"10\" style=\"height:100px; font-size:15px; width:450px\" placeholder=comment required>\r\n");
      out.write("</textarea><br>\r\n");
      out.write("<button>comment</button> \r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div align=\"center\" style=\"background-color:#F00\">\r\n");
      out.write(" All rights reserved. | Site best viewed with a resolution of 1024x768 (or higher) <a class=\"shl\" href=\"http://cbi.nic.in/disclaimer.php\">|Disclaimer</a> | \r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
